
# Eyes

- type: loadout
  id: SecurityClothingEyesGlasses
  equipment:
    eyes: ClothingEyesGlassesSecurity

# Hands

- type: loadout
  id: SecurityClothingHandsGlovesCombat
  equipment:
    gloves: ClothingHandsGlovesCombat

- type: loadout
  id: DetectiveClothingHandsGlovesForensic
  equipment:
    gloves: ClothingHandsGlovesForensic

# Outer Clothing

- type: loadout
  id: SecurityClothingOuterFullCoat
  effects:
  - !type:GroupLoadoutEffect
    proto: ContractorT1
  price: 600
  equipment:
    outerClothing: ClothingOuterSecurityFullCoat

- type: loadout
  id: HeadofSecurityClothingOuterFullCoat
  effects:
  - !type:GroupLoadoutEffect
    proto: ContractorT1
  price: 600
  equipment:
    outerClothing: ClothingOuterHoSFullCoat

# Shoes

- type: loadout
  id: HeadofSecurityClothingShoesWinter
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: ShoesCapableNF
  equipment:
    shoes: ClothingShoesBootsWinterHoS

- type: loadout
  id: WardenClothingShoesWinter
  hideEffects:
  - !type:GroupLoadoutEffect
    proto: ShoesCapableNF
  equipment:
    shoes: ClothingShoesBootsWinterWarden
